### PR TITLE
Fix some bugs in allowing to start/and/stop the handler

### PR DESCRIPTION
**Pull request by samyes**
* If at full volume while initializing, the system HUD would sometimes
incorrectly display the volume initialization back down to 0.99
 * In some cases (seemed to repro consistently on later iOS versions), the
volume was being incorrectly reset to either 0 or 0.5

### CODE REVIEW

**Comment by jpsim** [comment]
Code changes look good, but I haven't run myself to test. Assuming you're making these changes for a reason 😄 

Thanks for the PR!

**Comment by samyes** [comment]
Thanks! Making/testing the parallel changes in our local branch 😛

**Comment by jpsim** [comment]
I appreciate the contributions you've been making to this project, I've made you a collaborator to make it easier for you to continue your work on this, when necessary. Feel free to merge your own PRs unless you're explicitly soliciting reviews 😄

**Comment by samyes** [comment]
SGTM ✔

**Pull request merged**
